#!/bin/bash
docker build --build-arg CODE_RELEASE=2.1692-vsc1.39.2 \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VERSION=`git rev-parse --short HEAD` \
  -f $DOCKERFILE_PATH -t $IMAGE_NAME .
